In [ ]:
from google.colab import files
uploaded = files.upload()

Saving UCI_Credit_Card.csv to UCI_Credit_Card.csv

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Import Dataset**

In [ ]:
df_csv = pd.read_csv("/content/UCI_Credit_Card.csv")
df = pd.DataFrame(df_csv)

**Preprocessing**

In [ ]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [ ]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [ ]:
df.shape

(30000, 25)

In [ ]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default.payment.next.month'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   30000 non-null  float64
 14  BILL_AMT3                   30000 non-null  float64
 15  BILL_AMT4                   30000 non-null  float64
 16  BILL_AMT5                   30000 non-null  float64
 17  BILL_AMT6                   30000 non-null  float64
 18  PAY_AMT1                    30000 non-null  float64
 19  PAY_AMT2                    30000 non-null  float64
 20  PAY_AMT3                    30000 non-null  float64
 21  PAY_AMT4                    30000 non-null  float64
 22  PAY_AMT5                    30000 non-null  float64
 23  PAY_AMT6                    30000 non-null  float64
 24  default.payment.next.month  30000 non-null  int64
dtypes: float64(13), int64(12)
memory usage: 5.7 MB

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,30000.0,15000.500000,8660.398374,1.0,7500.75,15000.5,22500.25,30000.0
LIMIT_BAL,30000.0,167484.322667,129747.661567,10000.0,50000.00,140000.0,240000.00,1000000.0
SEX,30000.0,1.603733,0.489129,1.0,1.00,2.0,2.00,2.0
EDUCATION,30000.0,1.853133,0.790349,0.0,1.00,2.0,2.00,6.0
MARRIAGE,30000.0,1.551867,0.521970,0.0,1.00,2.0,2.00,3.0
AGE,30000.0,35.485500,9.217904,21.0,28.00,34.0,41.00,79.0
PAY_0,30000.0,-0.016700,1.123802,-2.0,-1.00,0.0,0.00,8.0
PAY_2,30000.0,-0.133767,1.197186,-2.0,-1.00,0.0,0.00,8.0
PAY_3,30000.0,-0.166200,1.196868,-2.0,-1.00,0.0,0.00,8.0
PAY_4,30000.0,-0.220667,1.169139,-2.0,-1.00,0.0,0.00,8.0
PAY_5,30000.0,-0.266200,1.133187,-2.0,-1.00,0.0,0.00,8.0
PAY_6,30000.0,-0.291100,1.149988,-2.0,-1.00,0.0,0.00,8.0
BILL_AMT1,30000.0,51223.330900,73635.860576,-165580.0,3558.75,22381.5,67091.00,964511.0
BILL_AMT2,30000.0,49179.075167,71173.768783,-69777.0,2984.75,21200.0,64006.25,983931.0
BILL_AMT3,30000.0,47013.154800,69349.387427,-157264.0,2666.25,20088.5,60164.75,1664089.0
BILL_AMT4,30000.0,43262.948967,64332.856134,-170000.0,2326.75,19052.0,54506.00,891586.0
BILL_AMT5,30000.0,40311.400967,60797.155770,-81334.0,1763.00,18104.5,50190.50,927171.0
BILL_AMT6,30000.0,38871.760400,59554.107537,-339603.0,1256.00,17071.0,49198.25,961664.0
PAY_AMT1,30000.0,5663.580500,16563.280354,0.0,1000.00,2100.0,5006.00,873552.0
PAY_AMT2,30000.0,5921.163500,23040.870402,0.0,833.00,2009.0,5000.00,1684259.0
PAY_AMT3,30000.0,5225.681500,17606.961470,0.0,390.00,1800.0,4505.00,896040.0
PAY_AMT4,30000.0,4826.076867,15666.159744,0.0,296.00,1500.0,4013.25,621000.0
PAY_AMT5,30000.0,4799.387633,15278.305679,0.0,252.50,1500.0,4031.50,426529.0
PAY_AMT6,30000.0,5215.502567,17777.465775,0.0,117.75,1500.0,4000.00,528666.0
default.payment.next.month,30000.0,0.221200,0.415062,0.0,0.00,0.0,0.00,1.0

In [ ]:
df.rename(columns = {"default.payment.next.month":"default"}, inplace = True)

In [ ]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default'],
      dtype='object')

In [ ]:
# df["default"].unique()
# default.payment.next.month = Will the customer miss (default on) next month’s payment?
df["default"].value_counts(normalize = True)

default
0    0.7788
1    0.2212
Name: proportion, dtype: float64

In [ ]:
bill_amt = [f"BILL_AMT{i}" for i in range(1,7)]
df["avg_bill_amt"] = df[bill_amt].mean(axis = 1)

In [ ]:
pay_amt = [f"PAY_AMT{i}" for i in range(1,7)]
df["avg_pay_amt"] = df[pay_amt].mean(axis=1)

In [ ]:
delay_amt = ['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']
df["max_delay"] = df[delay_amt].max(axis=1)

In [ ]:
df["payment_ratio"] = df["avg_pay_amt"]/(df["avg_bill_amt"]+1)

In [ ]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default,avg_bill_amt,avg_pay_amt,max_delay,payment_ratio
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,689.0,0.0,0.0,0.0,0.0,1,1284.000000,114.833333,2,0.089364
1,2,120000.0,2,2,2,26,-1,2,0,0,...,1000.0,1000.0,1000.0,0.0,2000.0,1,2846.166667,833.333333,2,0.292689
2,3,90000.0,2,2,2,34,0,0,0,0,...,1500.0,1000.0,1000.0,1000.0,5000.0,0,16942.166667,1836.333333,0,0.108382
3,4,50000.0,2,2,1,37,0,0,0,0,...,2019.0,1200.0,1100.0,1069.0,1000.0,0,38555.666667,1398.000000,0,0.036258
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,36681.0,10000.0,9000.0,689.0,679.0,0,18223.166667,9841.500000,0,0.540025

**Model training**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [ ]:
# train and test split
x = df.drop("default" ,axis =1)
y = df["default"]
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size =0.2,stratify = y, random_state = 42)

In [ ]:
# Column transform
num_features = x.columns

col_trans = ColumnTransformer(
    transformers=[
        ("scaler",StandardScaler(),num_features)
    ]
)

In [ ]:
# Baseline Model (random forest)
rf_pipe = Pipeline([
    ("col_transform",col_trans),
    ("model_rf",RandomForestClassifier(
        n_estimators=300,
        max_depth = 10,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

rf_pipe.fit(x_train,y_train)

Pipeline(steps=[('col_transform',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'avg_bill_amt', 'avg_pay_amt', 'max_delay', 'payment_ratio'],
      dtype='object'))])),
                ('model_rf',
                 RandomForestClassifier(class_weight='balanced', max_depth=10,
                                        n_estimators=300, n_jobs=-1,
                                        random_state=42))])

In [ ]:
# Advanced Model XGBoost
scal_pos_weight = df["default"].value_counts()[0] / df["default"].value_counts()[1]

xgb_pipe = Pipeline([
    ("col_transform",col_trans),
    ("xgb",XGBClassifier(
        n_estimators = 300,
        max_depth = 10,
        scale_pos_weight = scal_pos_weight,
        learning_rate = 0.05,
        subsample = 0.8,
        colsample_bytree = 0.8,
        random_state = 42,
        eval_metrics = "logloss"
    ))

])

xgb_pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [16:30:30] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Pipeline(steps=[('col_transform',
                 ColumnTransformer(transformers=[('scaler', StandardScaler(),
                                                  Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'avg_bill_amt...
                               eval_metrics='logloss', feature_types=None,
                               feature_weights=None, gamma=None,
                               grow_policy=None, importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=10, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=300, n_jobs=None, ...))])

In [36]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import RandomizedSearchCV

cv = StratifiedKFold(n_splits = 5, shuffle = True, random_state=42)

param_grid = {
    "xgb__n_estimators":[300,500,800],
    "xgb__learning_rate": [0.01, 0.05, 0.1],
    "xgb__max_depth": [3, 5, 7],
    "xgb__subsample": [0.7, 0.8, 1.0],
    "xgb__colsample_bytree": [0.7, 0.8, 1.0]
}

search = RandomizedSearchCV(
    xgb_pipe,
    param_distributions = param_grid,
    n_iter = 30,
    scoring = "roc_auc",
    cv= cv,
    n_jobs = 1,
    verbose = 2,
    random_state = 42
)

search.fit(x_train,y_train)

best_model = search.best_estimator_

Fitting 5 folds for each of 30 candidates, totalling 150 fits

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:01:09] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=0.7; total time=   9.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:01:19] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=0.7; total time=   7.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:01:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=0.7; total time=   9.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:01:36] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=0.7; total time=   9.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:01:45] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=0.7; total time=   7.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:01:53] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   4.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:01:57] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   2.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:01:59] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:03] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:06] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   4.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:10] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=1.0; total time=   3.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:14] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=1.0; total time=   3.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:17] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=1.0; total time=   5.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:23] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=1.0; total time=   4.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=1.0; total time=   3.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:31] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.8; total time=   6.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:37] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.8; total time=   4.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:41] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.8; total time=   4.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:46] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.8; total time=   5.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:52] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.8; total time=   4.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:02:56] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=0.8; total time=   7.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:03] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=0.8; total time=   5.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:08] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=0.8; total time=   7.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:15] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=0.8; total time=   5.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:21] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=0.8; total time=   7.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:28] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.8; total time=   2.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:31] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.8; total time=   2.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:34] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.8; total time=   3.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:37] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.8; total time=   5.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:42] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.8; total time=   2.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:44] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   9.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:03:54] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   7.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:01] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   9.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:10] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   9.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:20] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   7.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   5.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:37] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:41] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   5.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:46] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:50] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.7; total time=   1.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:52] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.7; total time=   1.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:53] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.7; total time=   1.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:04:55] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.7; total time=   8.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:03] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.7; total time=   1.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:05] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=1.0; total time=   1.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:06] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=1.0; total time=   1.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:07] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=1.0; total time=   3.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:10] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=1.0; total time=   1.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:12] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=1.0; total time=   1.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:13] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.7; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:16] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.7; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:18] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.7; total time=   4.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:23] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.7; total time=   3.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.7; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:28] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   3.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:31] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   5.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:37] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   3.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:40] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   3.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:43] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   3.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:46] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=1.0; total time=   3.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:49] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=1.0; total time=   1.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:51] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=1.0; total time=   1.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:52] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=1.0; total time=   1.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:54] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=1.0; total time=   1.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:56] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=1.0; total time=   2.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:05:58] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=1.0; total time=   3.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:01] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=1.0; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:04] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=1.0; total time=   2.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:06] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=1.0; total time=   2.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:08] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.8; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:09] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.8; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:10] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.8; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:11] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.8; total time=   1.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:12] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.8; total time=   2.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:15] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   6.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:21] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   8.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:29] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   6.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   8.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:44] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=800, xgb__subsample=1.0; total time=   6.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:50] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   4.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:55] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   2.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:06:58] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   2.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:01] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   3.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:04] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   4.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:09] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:12] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:16] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   5.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:22] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:25] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:29] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   4.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:36] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:38] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:40] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:43] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   4.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:48] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   2.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:50] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   2.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:53] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   4.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:07:58] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   3.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:01] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   2.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:03] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   2.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:05] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   2.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:07] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   3.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:11] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=800, xgb__subsample=0.7; total time=   2.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:13] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   3.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:16] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   3.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:19] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   5.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:24] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   3.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:28] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   3.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:31] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.7; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:32] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.7; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:32] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.7; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.7; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:34] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=0.7; total time=   3.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:38] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=0.7; total time=   1.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:39] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=0.7; total time=   1.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:40] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=0.7; total time=   1.4s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:42] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=0.7; total time=   1.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:43] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.05, xgb__max_depth=3, xgb__n_estimators=500, xgb__subsample=0.7; total time=   1.3s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:44] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=1.0; total time=   7.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:52] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=1.0; total time=   6.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:08:58] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=1.0; total time=   8.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:06] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=1.0; total time=   6.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:12] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=7, xgb__n_estimators=500, xgb__subsample=1.0; total time=   8.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:20] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=1.0; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:21] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=1.0; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:22] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=1.0; total time=   1.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:23] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=1.0; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:24] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=1.0, xgb__learning_rate=0.01, xgb__max_depth=3, xgb__n_estimators=300, xgb__subsample=1.0; total time=   0.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:25] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.8; total time=   1.9s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:27] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.8; total time=   3.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:30] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.8; total time=   1.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:32] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.8; total time=   1.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:33] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=300, xgb__subsample=0.8; total time=   1.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:35] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:37] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   4.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:42] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   3.1s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:45] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:47] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.7, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=0.8; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:50] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   2.8s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:53] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   5.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:09:58] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   2.7s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:10:00] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:10:03] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.01, xgb__max_depth=5, xgb__n_estimators=500, xgb__subsample=0.7; total time=   4.2s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:10:07] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   3.0s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:10:10] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:10:13] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   2.6s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:10:15] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   2.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:10:18] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[CV] END xgb__colsample_bytree=0.8, xgb__learning_rate=0.1, xgb__max_depth=7, xgb__n_estimators=300, xgb__subsample=1.0; total time=   4.5s

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [17:10:22] WARNING: /workspace/src/learner.cc:790:
Parameters: { "eval_metrics" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

**Model Evaluation**

In [ ]:
from sklearn.metrics import classification_report, roc_auc_score

In [37]:
def evaluate_train(model):
  preds = model.predict(x_train)
  probs = model.predict_proba(x_train)[:,1]

  print("Classification Report \n",classification_report(y_train,preds))
  print("ROC-AUC Score \n",roc_auc_score(y_train,probs))

print("random Forest")
evaluate_train(rf_pipe)
print("\n")
print("\n")

print("XGBoost")
evaluate_train(xgb_pipe)
print("\n")
print("\n")

print("Best Model")
evaluate_train(best_model)

random Forest
Classification Report
               precision    recall  f1-score   support

           0       0.91      0.87      0.89     18691
           1       0.61      0.69      0.65      5309

    accuracy                           0.83     24000
   macro avg       0.76      0.78      0.77     24000
weighted avg       0.84      0.83      0.84     24000

ROC-AUC Score
 0.8815230624763737




XGBoost
Classification Report
               precision    recall  f1-score   support

           0       1.00      0.98      0.99     18691
           1       0.94      1.00      0.97      5309

    accuracy                           0.99     24000
   macro avg       0.97      0.99      0.98     24000
weighted avg       0.99      0.99      0.99     24000

ROC-AUC Score
 0.9995139448983432




Best Model
Classification Report
               precision    recall  f1-score   support

           0       0.90      0.82      0.86     18691
           1       0.52      0.70      0.59      5309

    accuracy                           0.79     24000
   macro avg       0.71      0.76      0.73     24000
weighted avg       0.82      0.79      0.80     24000

ROC-AUC Score
 0.8513179700289585

In [38]:
def evaluate_test(model):
  preds = model.predict(x_test)
  probs = model.predict_proba(x_test)[:,1]

  print("Classification report", classification_report(y_test,preds))
  print("ROC AUC Score",roc_auc_score(y_test,probs))

print("Random Forest")
evaluate_test(rf_pipe)
print("\n")
print("\n")

print("XGBoost")
evaluate_test(xgb_pipe)
print("\n")
print("\n")

print("Best Model")
evaluate_train(best_model)

Random Forest
Classification report               precision    recall  f1-score   support

           0       0.87      0.84      0.86      4673
           1       0.51      0.57      0.54      1327

    accuracy                           0.78      6000
   macro avg       0.69      0.71      0.70      6000
weighted avg       0.79      0.78      0.79      6000

ROC AUC Score 0.7761794696432277




XGBoost
Classification report               precision    recall  f1-score   support

           0       0.86      0.88      0.87      4673
           1       0.54      0.50      0.52      1327

    accuracy                           0.79      6000
   macro avg       0.70      0.69      0.69      6000
weighted avg       0.79      0.79      0.79      6000

ROC AUC Score 0.7637509714047784




Best Model
Classification Report
               precision    recall  f1-score   support

           0       0.90      0.82      0.86     18691
           1       0.52      0.70      0.59      5309

    accuracy                           0.79     24000
   macro avg       0.71      0.76      0.73     24000
weighted avg       0.82      0.79      0.80     24000

ROC-AUC Score
 0.8513179700289585

In [39]:
# Threshold Optimization
from sklearn.metrics import f1_score

probs = best_model.predict_proba(x_test)[:,1]

threshold = np.arange(0.2,0.8, 0.05)
scores = [f1_score(y_test, probs>t) for t in threshold]

best_threshold = threshold[np.argmax(scores)]
best_threshold

np.float64(0.5499999999999999)